import { describe, expect, it } from "vitest";
import { CURRENT_SCHEMA_VERSION, createStableId, migrateProjectDocument, type ProjectDocument, validateProjectDocument } from "./index.js";
const id = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
function fixture(): ProjectDocument { const project = id(1), scene = id(2), root = id(3), image = id(4), asset = id(5), prefab = id(6); return { schemaVersion: CURRENT_SCHEMA_VERSION, project: { id: project, name: "Project" }, settings: { layoutProfileSelection: { mode: "aspect-ratio", mobileMaxAspectRatio: 1 } }, assets: [{ id: asset, name: "Logo", type: "image", source: { uri: "assets/logo.png", mediaType: "image/png" } }], prefabs: [{ id: prefab, name: "Badge", rootNodeIds: [], nodes: [], exposedProperties: [] }], scenes: [{ id: scene, name: "Main", rootNodeIds: [root], layout: { referenceViewports: { desktop: { width: 1920, height: 1080 }, mobile: { width: 390, height: 844 } } }, nodes: [{ id: root, name: "Root", type: "container", parentId: null, children: [image], visible: true, transform: { x: 0, y: 0, width: 100, height: 100, scaleX: 1, scaleY: 1, rotation: 0 } }, { id: image, name: "Logo", type: "image", assetId: asset, parentId: root, children: [], visible: true, transform: { x: 0, y: 0, width: 10, height: 10, scaleX: 1, scaleY: 1, rotation: 0 } }] }] }; }
const check = (fn: (x: ProjectDocument) => void) => { const x = fixture(); fn(x); return validateProjectDocument(x); };
describe("schema v0", () => {
  it("generates independent UUID stable IDs", () => { const a = createStableId(), b = createStableId(); expect(a).toMatch(/^[0-9a-f]{8}-/i); expect(a).not.toBe(b); });
  it("accepts a minimal valid document", () => expect(validateProjectDocument(fixture())).toEqual({ valid: true, issues: [] }));
  it.each(["desktop", "mobile"])("rejects missing %s viewport", (profile) => { const result = check((x) => delete (x.scenes[0]!.layout.referenceViewports as Record<string, unknown>)[profile]); expect(result.issues[0]!.code).toBe("STRUCTURAL_SCHEMA"); });
  it("reports duplicate IDs", () => { const r = check((x) => { x.scenes[0]!.nodes[1]!.id = x.scenes[0]!.nodes[0]!.id; }); expect(r.issues.some((x) => x.code === "DUPLICATE_ID")).toBe(true); });
  it("reports missing child and asset references", () => { const r = check((x) => { x.scenes[0]!.nodes[0]!.children = [id(99)]; (x.scenes[0]!.nodes[1] as { assetId: string }).assetId = id(98); }); expect(r.issues.map((x) => x.code)).toEqual(expect.arrayContaining(["MISSING_CHILD_REFERENCE", "MISSING_ASSET_REFERENCE"])); });
  it("reports missing prefab references", () => { const r = check((x) => { x.scenes[0]!.nodes[1] = { ...x.scenes[0]!.nodes[1]!, type: "prefab-instance", prefabId: id(99) }; }); expect(r.issues.some((x) => x.code === "MISSING_PREFAB_REFERENCE")).toBe(true); });
  it("reports inconsistent parent and children", () => { const r = check((x) => { x.scenes[0]!.nodes[1]!.parentId = null; }); expect(r.issues.some((x) => x.code === "HIERARCHY_PARENT_MISMATCH")).toBe(true); });
  it("reports cycles", () => { const r = check((x) => { const n = x.scenes[0]!.nodes; n[0]!.parentId = n[1]!.id; n[1]!.children = [n[0]!.id]; }); expect(r.issues.some((x) => x.code === "HIERARCHY_CYCLE")).toBe(true); });
  it("reports duplicate bindings", () => { const r = check((x) => { x.scenes[0]!.nodes[0]!.binding = "target"; x.scenes[0]!.nodes[1]!.binding = "target"; }); expect(r.issues.some((x) => x.code === "DUPLICATE_BINDING")).toBe(true); });
  it("rejects unknown profile keys and schema versions", () => { const r = check((x) => { x.scenes[0]!.nodes[0]!.layoutOverrides = { tablet: {} } as never; (x as { schemaVersion: number }).schemaVersion = 1; }); expect(r.issues.some((x) => x.code === "STRUCTURAL_SCHEMA")).toBe(true); });
  it("migrates v0 without mutating input", () => { const input = fixture(), output = migrateProjectDocument(input); expect(output).toEqual(input); expect(output).not.toBe(input); output.project.name = "Changed"; expect(input.project.name).toBe("Project"); });
});
