import type { StoreApi } from "zustand";
import type { AssetFile, ButtonStateKey, GridLayoutSettings, InputNode, LayoutGroupNode, LayoutItemDefinition, LayoutProfileId, LinearLayoutSettings, PrefabDefinition, ProjectDocument, Scene, ScrollViewSettings, TextStyleDefinition, UINode } from "@pixi-ui-editor/schema";
export const DOCUMENT_STORAGE_KEY = "pixi-ui-editor:document";
export type EditorTool = "pan" | "select" | "resize";
export type ViewMode = "single" | "map";
export type AddableNodeType = "container" | "horizontal-layout" | "vertical-layout" | "grid-layout" | "scroll-view" | "image" | "text" | "spine" | "button" | "input";
export type InputPatch = Partial<Pick<InputNode, "backgroundAssetId" | "placeholder" | "defaultValue" | "maxLength" | "secure" | "align" | "padding" | "cleanOnFocus" | "clipText" | "textStyle">>;

export type EditorState = {
  document: ProjectDocument;
  sceneId: string;
  activeProfile: LayoutProfileId;
  activeTool: EditorTool;
  viewMode: ViewMode;
  selectedNodeIds: string[];
  selectedNodeId: string | null;
  editingPrefabId: string | null;
  spineFrameRequests: Record<string, number>;
  spinePlaybackFrames: Record<string, { current: number; total: number }>;
  spineAutoplay: Record<string, boolean>;
  /** Transient authoring aid: shows one button state on the canvas. Never serialized. */
  buttonPreviewStates: Record<string, ButtonStateKey>;
  setActiveProfile(profile: LayoutProfileId): void;
  setActiveTool(tool: EditorTool): void;
  setViewMode(mode: ViewMode): void;
  selectNode(id: string | null, additive?: boolean): void;
  selectNodes(ids: string[], additive?: boolean): void;
  selectScene(sceneId: string): void;
  addScene(name?: string): void;
  renameScene(sceneId: string, name: string): void;
  deleteScene(sceneId: string): void;
  updateReferenceViewport(profile: LayoutProfileId, viewport: { width: number; height: number }): void;
  updateNode(nodeId: string, patch: Partial<Pick<UINode, "name" | "visible">> & { text?: string; style?: TextStyleDefinition }): void;
  updateNodeProfileTransform(nodeId: string, patch: Partial<UINode["transform"]>): void;
  updateNodeProfileTransforms(updates: { nodeId: string; patch: Partial<UINode["transform"]> }[]): void;
  updateLayoutGroup(nodeId: string, patch: Partial<LinearLayoutSettings | GridLayoutSettings>): void;
  updateLayoutItem(nodeId: string, patch: Partial<LayoutItemDefinition>): void;
  setLayoutGroupBackgroundAsset(nodeId: string, assetId: string | undefined): void;
  updateScrollView(nodeId: string, patch: Partial<ScrollViewSettings>): void;
  updateInput(nodeId: string, patch: InputPatch): void;
  setNodeProfileAnchor(nodeId: string, anchor: AnchorRect, options: { setPivot: boolean; snap: boolean }): void;
  setNodeOrientationVisibility(nodeId: string, profile: LayoutProfileId, visible: boolean): void;
  addImageAsset(name: string, source: { uri: string; mediaType: string }): void;
  addFontAsset(name: string, family: string, weight: "normal" | "bold", style: "normal" | "italic", source: { uri: string; mediaType: string }): void;
  addSpineAsset(name: string, files: { skeleton: AssetFile; atlas: AssetFile; textures: AssetFile[] }): void;
  setImageNodeAsset(nodeId: string, assetId: string): void;
  replaceAssetSource(assetId: string, source: { uri: string; mediaType: string }): void;
  replaceSpineAssetFiles(assetId: string, files: { skeleton: AssetFile; atlas: AssetFile; textures: AssetFile[] }): void;
  deleteAsset(assetId: string): void;
  updateSpineNodeAnimation(nodeId: string, animation: string | undefined): void;
  updateSpineNodeLoop(nodeId: string, loop: boolean): void;
  requestSpineFrame(nodeId: string, frame: number): void;
  setSpineAutoplay(nodeId: string, autoplay: boolean): void;
  reportSpinePlaybackFrame(nodeId: string, playback: { current: number; total: number }): void;
  setButtonStateAsset(nodeId: string, state: ButtonStateKey, assetId: string | undefined): void;
  setButtonEnabled(nodeId: string, enabled: boolean): void;
  previewButtonState(nodeId: string, state: ButtonStateKey): void;
  addNode(type: AddableNodeType): void;
  addNodeFromAsset(assetId: string, position: { x: number; y: number }): void;
  moveNode(nodeId: string, placement: { parentId: string | null; index: number }): void;
  deleteNode(nodeId: string): void;
  createPrefabFromNode(nodeId: string): string | null;
  addPrefabInstance(prefabId: string, position: { x: number; y: number }): void;
  renamePrefab(prefabId: string, name: string): void;
  deletePrefab(prefabId: string): void;
  setEditingPrefabId(prefabId: string | null): void;
};

export type EditingTarget = Scene | PrefabDefinition;
export type AnchorRect = { minX: number; minY: number; maxX: number; maxY: number };
export type EditorSlice<K extends keyof EditorState> = (set: StoreApi<EditorState>["setState"], get: StoreApi<EditorState>["getState"]) => Pick<EditorState, K>;
